import { Story } from "../types";

export const STORIES: Story[] = [
  {
    id: 1,
    username: "sarah",
    avatar: "https://i.pravatar.cc/150?img=1",
    hasStory: true,
  },
  {
    id: 2,
    username: "mike",
    avatar: "https://i.pravatar.cc/150?img=2",
    hasStory: true,
  },
  {
    id: 3,
    username: "emma",
    avatar: "https://i.pravatar.cc/150?img=3",
    hasStory: true,
  },
  {
    id: 4,
    username: "jake",
    avatar: "https://i.pravatar.cc/150?img=4",
    hasStory: true,
  },
  {
    id: 5,
    username: "lily",
    avatar: "https://i.pravatar.cc/150?img=5",
    hasStory: true,
  },
  {
    id: 6,
    username: "noah",
    avatar: "https://i.pravatar.cc/150?img=6",
    hasStory: true,
  },
  {
    id: 7,
    username: "olivia",
    avatar: "https://i.pravatar.cc/150?img=7",
    hasStory: true,
  },
  {
    id: 8,
    username: "ethan",
    avatar: "https://i.pravatar.cc/150?img=8",
    hasStory: true,
  },
  {
    id: 9,
    username: "ava",
    avatar: "https://i.pravatar.cc/150?img=9",
    hasStory: true,
  },
  {
    id: 10,
    username: "liam",
    avatar: "https://i.pravatar.cc/150?img=10",
    hasStory: true,
  },
  {
    id: 11,
    username: "mia",
    avatar: "https://i.pravatar.cc/150?img=11",
    hasStory: true,
  },
  {
    id: 12,
    username: "james",
    avatar: "https://i.pravatar.cc/150?img=12",
    hasStory: true,
  },
  {
    id: 13,
    username: "sophia",
    avatar: "https://i.pravatar.cc/150?img=13",
    hasStory: true,
  },
  {
    id: 14,
    username: "ben",
    avatar: "https://i.pravatar.cc/150?img=14",
    hasStory: true,
  },
  {
    id: 15,
    username: "isabella",
    avatar: "https://i.pravatar.cc/150?img=15",
    hasStory: true,
  },
  {
    id: 16,
    username: "lucas",
    avatar: "https://i.pravatar.cc/150?img=16",
    hasStory: true,
  },
  {
    id: 17,
    username: "charlotte",
    avatar: "https://i.pravatar.cc/150?img=17",
    hasStory: true,
  },
  {
    id: 18,
    username: "henry",
    avatar: "https://i.pravatar.cc/150?img=18",
    hasStory: true,
  },
  {
    id: 19,
    username: "amelia",
    avatar: "https://i.pravatar.cc/150?img=19",
    hasStory: true,
  },
  {
    id: 20,
    username: "alex",
    avatar: "https://i.pravatar.cc/150?img=20",
    hasStory: true,
  },
  {
    id: 21,
    username: "harper",
    avatar: "https://i.pravatar.cc/150?img=21",
    hasStory: true,
  },
  {
    id: 22,
    username: "daniel",
    avatar: "https://i.pravatar.cc/150?img=22",
    hasStory: true,
  },
  {
    id: 23,
    username: "evelyn",
    avatar: "https://i.pravatar.cc/150?img=23",
    hasStory: true,
  },
  {
    id: 24,
    username: "jack",
    avatar: "https://i.pravatar.cc/150?img=24",
    hasStory: true,
  },
  {
    id: 25,
    username: "grace",
    avatar: "https://i.pravatar.cc/150?img=25",
    hasStory: true,
  },
  {
    id: 26,
    username: "logan",
    avatar: "https://i.pravatar.cc/150?img=26",
    hasStory: true,
  },
  {
    id: 27,
    username: "zoe",
    avatar: "https://i.pravatar.cc/150?img=27",
    hasStory: true,
  },
  {
    id: 28,
    username: "will",
    avatar: "https://i.pravatar.cc/150?img=28",
    hasStory: true,
  },
  {
    id: 29,
    username: "nora",
    avatar: "https://i.pravatar.cc/150?img=29",
    hasStory: true,
  },
  {
    id: 30,
    username: "owen",
    avatar: "https://i.pravatar.cc/150?img=30",
    hasStory: true,
  },
  {
    id: 31,
    username: "ella",
    avatar: "https://i.pravatar.cc/150?img=31",
    hasStory: true,
  },
  {
    id: 32,
    username: "sam",
    avatar: "https://i.pravatar.cc/150?img=32",
    hasStory: true,
  },
  {
    id: 33,
    username: "luna",
    avatar: "https://i.pravatar.cc/150?img=33",
    hasStory: true,
  },
  {
    id: 34,
    username: "mason",
    avatar: "https://i.pravatar.cc/150?img=34",
    hasStory: true,
  },
  {
    id: 35,
    username: "chloe",
    avatar: "https://i.pravatar.cc/150?img=35",
    hasStory: true,
  },
  {
    id: 36,
    username: "ryan",
    avatar: "https://i.pravatar.cc/150?img=36",
    hasStory: true,
  },
  {
    id: 37,
    username: "layla",
    avatar: "https://i.pravatar.cc/150?img=37",
    hasStory: true,
  },
  {
    id: 38,
    username: "leo",
    avatar: "https://i.pravatar.cc/150?img=38",
    hasStory: true,
  },
  {
    id: 39,
    username: "violet",
    avatar: "https://i.pravatar.cc/150?img=39",
    hasStory: true,
  },
  {
    id: 40,
    username: "gabe",
    avatar: "https://i.pravatar.cc/150?img=40",
    hasStory: true,
  },
  {
    id: 41,
    username: "hannah",
    avatar: "https://i.pravatar.cc/150?img=41",
    hasStory: true,
  },
  {
    id: 42,
    username: "eli",
    avatar: "https://i.pravatar.cc/150?img=42",
    hasStory: true,
  },
  {
    id: 43,
    username: "aria",
    avatar: "https://i.pravatar.cc/150?img=43",
    hasStory: true,
  },
  {
    id: 44,
    username: "carter",
    avatar: "https://i.pravatar.cc/150?img=44",
    hasStory: true,
  },
  {
    id: 45,
    username: "scarlett",
    avatar: "https://i.pravatar.cc/150?img=45",
    hasStory: true,
  },
  {
    id: 46,
    username: "dylan",
    avatar: "https://i.pravatar.cc/150?img=46",
    hasStory: true,
  },
  {
    id: 47,
    username: "piper",
    avatar: "https://i.pravatar.cc/150?img=47",
    hasStory: true,
  },
  {
    id: 48,
    username: "max",
    avatar: "https://i.pravatar.cc/150?img=48",
    hasStory: true,
  },
  {
    id: 49,
    username: "sadie",
    avatar: "https://i.pravatar.cc/150?img=49",
    hasStory: true,
  },
  {
    id: 50,
    username: "finn",
    avatar: "https://i.pravatar.cc/150?img=50",
    hasStory: true,
  },
];
